[tool.towncrier]
name = "VTS-SimPipe"
directory = "docs/changes"
filename = "CHANGELOG.md"
underlines = [ "", "", "" ]
title_format = "## [{version}](https://github.com/VERITAS-Observatory/VTS-SimPipe/releases/tag/{version}) - {project_date}"
issue_format = "[#{issue}](https://github.com/VERITAS-Observatory/VTS-SimPipe/issues/{issue})"
start_string = "<!-- towncrier release notes start -->\n"

[tool.towncrier.fragment.feature]
name = "New Feature"
showcontent = true

[tool.towncrier.fragment.bugfix]
name = "Bugfixes"
showcontent = true

[tool.towncrier.fragment.maintenance]
name = "Maintenance"
showcontent = true

[tool.towncrier.fragment.doc]
name = "Documentation"
showcontent = true

[tool.towncrier.fragment.api]
name = "API Changes"
showcontent = true
